# Generated by Django 2.2.4 on 2019-12-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaceApp', '0004_auto_20191218_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
    ]
